### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'notes')

### ISSUE THREAD

**Issue by c939984606** [pengzhanbo/vuepress-theme-plume#15]
TypeError: Cannot read properties of undefined (reading 'notes')
    at file:///E:/Github/docs/node_modules/@vuepress-plume/vuepress-theme-plume/lib/node/autoFrontmatter.js:26:53
    at Array.map (<anonymous>)
    at autoFrontmatter (file:///E:/Github/docs/node_modules/@vuepress-plume/vuepress-theme-plume/lib/node/autoFrontmatter.js:25:10)
    at setupPlugins (file:///E:/Github/docs/node_modules/@vuepress-plume/vuepress-theme-plume/lib/node/plugins.js:46:31)
    at file:///E:/Github/docs/node_modules/@vuepress-plume/vuepress-theme-plume/lib/node/theme.js:25:22
    at resolvePluginObject (file:///E:/Github/docs/node_modules/@vuepress/core/dist/index.js:635:65)
    at resolveThemeInfo (file:///E:/Github/docs/node_modules/@vuepress/core/dist/index.js:927:23)
    at setupAppThemeAndPlugins (file:///E:/Github/docs/node_modules/@vuepress/core/dist/index.js:946:21)
    at createBaseApp (file:///E:/Github/docs/node_modules/@vuepress/core/dist/index.js:975:3)
    at createBuildApp (file:///E:/Github/docs/node_modules/@vuepress/core/dist/index.js:981:15)

**Comment by c939984606** [comment]
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@vuepress/client": "2.0.0-beta.66",
    "@vuepress/plugin-back-to-top": "2.0.0-beta.66",
    "@vuepress/plugin-external-link-icon": "2.0.0-beta.66",
    "@vuepress/plugin-medium-zoom": "2.0.0-beta.66",
    "@vuepress/plugin-shiki": "2.0.0-beta.66",
    "vue": "^3.3.4",
    "vuepress": "2.0.0-beta.66",
    "vuepress-plugin-clipboard": "^2.1.5"
  }
}
```

**Comment by pengzhanbo** [comment]
The issue has been fixed
