### ISSUE TITLE
在使用 typecho 编写文档时，程序会崩溃

### ISSUE THREAD

**Issue by huankong233** [pengzhanbo/vuepress-theme-plume#17]
可以加一个选项来选择excude选项吗

https://github.com/pengzhanbo/vuepress-theme-plume/blob/f746d4614125f98467a05d546ee4a8d6cd4cd8fb/packages/theme/src/node/autoFrontmatter.ts#L88-L175

在我使用 typecho 编写文档时，程序会崩溃

我翻了一下源码，我看到可以配置不监控哪些文件

https://github.com/pengzhanbo/vuepress-theme-plume/blob/f746d4614125f98467a05d546ee4a8d6cd4cd8fb/packages/plugin-auto-frontmatter/src/node/plugin.ts#L18

## 报错日志
~~~
❯ pd

> blog@1.0.0 dev C:\Users\huan_kong\Desktop\code\blog
> vuepress dev src --clean-cache --clean-temp

✔ Cleaning temp - done in 30ms
✔ Cleaning cache - done in 5ms
✔ Initializing and preparing data - done in 4.50s

  vite v4.4.11 dev server running at:

  ➜  Local:   http://localhost:8081/
  ➜  Network: http://192.168.31.104:8081/
  ➜  Network: http://172.22.132.245:8081/
info page note\algorithm\2.数据结构\数组.md is created
info page note\algorithm\2.数据结构\数组.md is modified
info page note\algorithm\2.数据结构\1.数组.md is removed
10:40:20 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/pagesComponents.
10:40:20 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/pagesData.js
10:40:20 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/pagesRoutes.js
10:40:20 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/notesData.js
10:40:20 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/blogData.js
10:40:20 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/pagesComponents.
10:40:20 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/pagesData.js
10:40:20 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/pagesRoutes.js
node:fs:1690
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat 'C:\Users\huan_kong\Desktop\code\blog\src\note\algorithm\2.数据md'
    at Object.statSync (node:fs:1690:3)
    at readMarkdown (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/@vuepress-plume+vuepress-frontmatter@1.0.0-beta.85/node_modules/@vuepress-plume/vuepress-plugin-auto-frontmatter/lib/node/readFiles.js:
    at FSWatcher.<anonymous> (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/@vuepress-plume+gin-auto-frontmatter@1.0.0-beta.85/node_modules/@vuepress-plume/vuepress-plugin-auto-frontmatter/lib/node/plug    at FSWatcher.emit (node:events:514:28)
    at FSWatcher.emitWithAll (C:\Users\huan_kong\Desktop\code\blog\node_modules\.pnpm\chokidar@3.5.3\node_modu\index.js:540:8)
    at FSWatcher._emit (C:\Users\huan_kong\Desktop\code\blog\node_modules\.pnpm\chokidar@3.5.3\node_modules\ch.js:632:8)
    at NodeFsHandler._handleFile (C:\Users\huan_kong\Desktop\code\blog\node_modules\.pnpm\chokidar@3.5.3\node_idar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (C:\Users\huan_kong\Desktop\code\blog\node_modules\.pnpm\chokidar@3.5.3\nodekidar\lib\nodefs-handler.js:637:21) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\huan_kong\\Desktop\\code\\blog\\src\\note\\algorithm\\2.数据结构\\.~数组.md'
}
~~~

**Comment by pengzhanbo** [comment]
👍

**Comment by huankong233** [comment]
> 👍 已合并发布。

🤝
