### ISSUE TITLE
使用 `Typora` 编写文档 并使用 `PicGo` 上传图片导致报错

### ISSUE THREAD

**Issue by huankong233** [pengzhanbo/vuepress-theme-plume#21]
问题如题，报错代码:

~~~
========================= ↓ 图片复制到了文档内
info page note\algorithm\2.数据结构\链表.md is modified
15:00:01 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/notesData.js
15:00:01 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/blogData.js
15:00:01 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/pages/note/algorithm/数据结构/链
表/index.html.vue
15:00:01 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/pages/note/algorithm/数据结构/链
表/index.html.js
15:00:02 [vite] Internal server error: Failed to resolve import "@source/note/algorithm/2.数据结构/C:/Users/huan_kong/AppData/Roaming/Typora/typora-user-images/image-20231127150000447.png" from "src\.vuepress\.temp\pages\note\algorithm\数据结
构\链表\index.html.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/pages/note/algorithm/数据结构/链表/index.html.vue:3:25  
  1  |  const _sfc_main = {}
  2  |  import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
  3  |  import _imports_0 from '@source/note/algorithm/2.数据结构/C:/Users/huan_kong/AppData/Roaming/Typora/typora-user-images/image-20231127150000447.png'
     |                          ^
  4  |
  5  |
      at formatError (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:61701:46)
      at TransformContext.error (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:61695:19)
      at normalizeUrl (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:59988:33)
      at async file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:60138:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:60059:13)
      at async Object.transform (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:61996:30)
      at async loadAndTransform (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:47780:29)
      at async viteTransformMiddleware (file:///C:/Users/huan_kong/Desktop/code/blog/node_modules/.pnpm/vite@5.0.0_@types+node@18.18.10/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:57379:32)
========================= ↓ 上传完成
info page note\algorithm\2.数据结构\链表.md is modified
15:00:03 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/notesData.js
15:00:03 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/internal/blogData.js
15:00:03 [vite] page reload C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/pages/note/algorithm/数据结构/链表/index.html.vue
15:00:03 [vite] hmr update /@fs/C:/Users/huan_kong/Desktop/code/blog/src/.vuepress/.temp/pages/note/algorithm/数据结构/链
表/index.html.js
~~~

虽然不会导致崩溃，但是有点像狗皮膏药，看着难受

**Comment by huankong233** [comment]
在图片偏好中选择 `优先相对路径` 即可
![image](https://github.com/pengzhanbo/vuepress-theme-plume/assets/49610758/8daa394f-3b31-467a-9bce-268489d8e33b)
