### ISSUE TITLE
[Bug] 升级至rc.115版本后@vuepress/plugin-git插件无法通过build编译

### ISSUE THREAD

**Issue by dingyuqi** [pengzhanbo/vuepress-theme-plume#334]
### 检查清单

- [X] 我正在使用**LTS**版本的Node.js。
- [X] 我正在使用 **最新 v2 版本** 的 VuePress 和 VuePress 官方插件。
- [X] 我正在使用此仓库中的 **最新版本** 的 vuepress-theme-plume 及其所有插件。
- [X] 我按照文档操作，并仔细检查了我的配置。

### 包名

vuepress-theme-plume

### 你正在使用哪个操作系统？

- [ ] macOS
- [X] Windows
- [ ] Linux

### 描述该错误

我开启了contributor和changlog, 在`pnpm docs:dev`时插件表现正常, 但是部署时发生错误. 我想可能哪里出现了问题. 似乎build的编译更加严格所以在开发环境没有出现问题, 但是生产环境出现了.
```
error error in hook extendsPage from @vuepress/plugin-git
✖ Initializing and preparing data - failed in 5.27s
error Error [ERR_CRYPTO_HASH_FINALIZED]: Digest already called
    at Hash.update (node:internal/crypto/hash:110:11)
    at digestSHA256 (file:///vercel/path0/node_modules/.pnpm/@vuepress+plugin-git@2.0.0-rc.60_vuepress@2.0.0-rc.18_@vuepress+bundler-vite@2.0.0-rc.18_@typ_bvhdvyxzzgd332widp4h6sr4ci/node_modules/@vuepress/plugin-git/lib/node/utils/digestSHA256.js:4:10)
    at getRawContributors (file:///vercel/path0/node_modules/.pnpm/@vuepress+plugin-git@2.0.0-rc.60_vuepress@2.0.0-rc.18_@vuepress+bundler-vite@2.0.0-rc.18_@typ_bvhdvyxzzgd332widp4h6sr4ci/node_modules/@vuepress/plugin-git/lib/node/resolveContributors.js:28:66)
    at resolveContributors (file:///vercel/path0/node_modules/.pnpm/@vuepress+plugin-git@2.0.0-rc.60_vuepress@2.0.0-rc.18_@vuepress+bundler-vite@2.0.0-rc.18_@typ_bvhdvyxzzgd332widp4h6sr4ci/node_modules/@vuepress/plugin-git/lib/node/resolveContributors.js:55:26)
    at Object.extendsPage [as hook] (file:///vercel/path0/node_modules/.pnpm/@vuepress+plugin-git@2.0.0-rc.60_vuepress@2.0.0-rc.18_@vuepress+bundler-vite@2.0.0-rc.18_@typ_bvhdvyxzzgd332widp4h6sr4ci/node_modules/@vuepress/plugin-git/lib/node/gitPlugin.js:47:46)
    at async Object.process (file:///vercel/path0/node_modules/.pnpm/@vuepress+core@2.0.0-rc.18_typescript@5.6.2/node_modules/@vuepress/core/dist/index.js:664:26)
    at async createPage (file:///vercel/path0/node_modules/.pnpm/@vuepress+core@2.0.0-rc.18_typescript@5.6.2/node_modules/@vuepress/core/dist/index.js:430:3)
    at async file:///vercel/path0/node_modules/.pnpm/@vuepress+core@2.0.0-rc.18_typescript@5.6.2/node_modules/@vuepress/core/dist/index.js:561:20
    at async Promise.all (index 69)
    at async resolveAppPages (file:///vercel/path0/node_modules/.pnpm/@vuepress+core@2.0.0-rc.18_typescript@5.6.2/node_modules/@vuepress/core/dist/index.js:559:17)
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run docs:build" exited with 1
```

**Comment by pengzhanbo** [comment]
这里是发生了 计算字符串 sha256 值时，摘要被消费后又再次调用导致的报错。

这个问题需要到 `vuepress/ecosystem` 仓库那边去修复。暂时没那么快可以解决。

以下是临时的可以解决的方式：

你的仓库如果是托管在非 github 的其他地方，需要在 [`contributors.info`](https://theme-plume.vuejs.press/guide/features/contributors/#info) 中先预设好 贡献者的信息，包括 __头像地址__。

由于非 github 的头像地址没法直接根据 `username` 得到，当你没设置时，插件只能通过 email 或 username 计算 sha256 值，获取一个临时的头像地址。 因此，你手动设置好头像地址，就可以规避这个报错。

**Comment by dingyuqi** [comment]
非常感谢. 不过我的仓库是托管在GitHub上的, 但是也发生了这个问题. 我想如果无法获取头像的连接的话, 那应该在dev模式下就出现报错.
可是dev模式下头像显示完全正常, 也可以进行跳转.

**Comment by dingyuqi** [comment]
我已经解决该问题. 导致问题的原因是我本地拥有两套git账户, 一个是工作账户提交gitlab, 一个是个人的提交GitHub.
虽然该项目托管在GitHub上, 也使用的是个人账户在提交, 但是我认为插件应该是获取到了错误的git账户.

不过目前问题已经解决. 非常感谢您的帮助.

pengzhanbo ***@***.***> 于2024年11月11日周一 11:47写道：

**Comment by pengzhanbo** [comment]
你可以运行下 `git remote get-url origin` 看看输出的 仓库信息是否包含 `github.com` ，我怀疑大概率没有被识别为 github，而是被识别为 未知，即可能是 内建的 git 托管服务。

**Comment by dingyuqi** [comment]
> 你可以运行下 `git remote get-url origin` 看看输出的 仓库信息是否包含 `github.com` ，我怀疑大概率没有被识别为 github，而是被识别为 未知，即可能是 内建的私有 git 托管服务。

这一部分是被确认的, 仓库信息包含github.com. 该问题可能需要更多的排查. 可能多个git账户产生了问题.

**Comment by pengzhanbo** [comment]
git 插件仅在启动时，执行 git remote get-url origin 来确认 托管服务的供应商，包括 github、gitlab、gitee、或者 null 等，后续的其他操作依赖于 gitProvider 进行。

存在多个 git 账户 这个不是问题，因为你在 commit 时提交者肯定是只有一个的，而且也不从这里判断 git 供应商。
在 commit 中确认 username 后，会根据 gitProvider 来添加其它信息。

一个 git 仓库是可能存在多个远程仓库地址的。 插件默认读取的 origin 的配置，但也可能 origin 不存在，然后通过 `git remote -v` 来获取 远程仓库列表，然取出第一个重新执行 `git remote get-url xxx` 来判断最终的 git provider。

---

我会怀疑没有被识别为 github 是因为，我进入你的博客，从页面的 changelog 中：
![QQ_1731306334647](https://github.com/user-attachments/assets/f3363688-c315-4385-b7b3-d1ffe78e7448)
并没有正确生成 release tag 的跳转链接。但插件在这里是有预设 连接生成规则的，如果是 github，那么这里应该是一个可跳转的链接，而不是一个 span 标签。

**Comment by dingyuqi** [comment]
感谢你的解释, 我大致理解为什么我会出现问题. 

我将代码托管在GitHub上, 但是没有提交 `.git` 文件夹. 但是我的部署是使用 vercel 进行部署. 所以我本地运行 `pnpm docs:dev` 时一切正常, 但是 vercel 运行 `pnpm docs:build` 的时候无法获取 git 的相关信息, 导致了无法解析的问题.

我尝试对其在config中进行一定的配置. 但是似乎还是一个 span 的标签.
https://github.com/dingyuqi/blog-with-plume-theme/blob/main/docs/.vuepress/theme.ts

**Comment by pengzhanbo** [comment]
似乎在 vercel 中执行 构建，无法获取到 git 的 commit 记录。这导致了 changelog 生成了错误的数据。
在你的仓库中并不存在 `grafted tag`。

如果你希望有正确的 changelog，我建议你可以参考主题仓库的构建部署模式。

1. 在 github actions 构建输出到 特定的分支。
2. 在 vercel 上配置生产分支为 这个特定分支，并直接使用这个分支的文件进行部署，无需在 vercel 上编译构建。

**Comment by pecliu** [comment]
> 这里是发生了 计算字符串 sha256 值时，摘要被消费后又再次调用导致的报错。
> 
> 这个问题需要到 `vuepress/ecosystem` 仓库那边去修复。暂时没那么快可以解决。
> 
> 以下是临时的可以解决的方式：
> 
> 你的仓库如果是托管在非 github 的其他地方，需要在 [`contributors.info`](https://theme-plume.vuejs.press/guide/features/contributors/#info) 中先预设好 贡献者的信息，包括 **头像地址**。
> 
> 由于非 github 的头像地址没法直接根据 `username` 得到，当你没设置时，插件只能通过 email 或 username 计算 sha256 值，获取一个临时的头像地址。 因此，你手动设置好头像地址，就可以规避这个报错。

请问有办法直接动态转换 username 的 avatar 吗？ 比如 avatar 的地址其实是固定链接+username。而贡献者数量和人员都不可知，希望可以自动转换

**Comment by Yu2002s** [comment]
我丢，这个问题搞了我半天，最后还是降版本解决了。
