### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YuChuanhui3** [pengzhanbo/vuepress-theme-plume#343]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest version** of vuepress-theme-plume and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.

### Package name

vuepress-theme-plume

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

 Initializing and preparing dataError: what the crap: date
    at C:\Project\note\node_modules\json2yaml\index.js:84:21
    at Array.forEach (<anonymous>)
    at Object.object (C:\Project\note\node_modules\json2yaml\index.js:69:26)
    at Object.stringify (C:\Project\note\node_modules\json2yaml\index.js:99:42)
    at generator (file:///C:/Project/note/node_modules/vuepress-theme-plume/lib/node/index.js:1223:56)
Error: what the crap: date
    at C:\Project\note\node_modules\json2yaml\index.js:84:21
    at Array.forEach (<anonymous>)
    at Object.object (C:\Project\note\node_modules\json2yaml\index.js:69:26)
    at Object.stringify (C:\Project\note\node_modules\json2yaml\index.js:99:42)
    at generator (file:///C:/Project/note/node_modules/vuepress-theme-plume/lib/node/index.js:1223:56)

**Comment by YuChuanhui3** [comment]
createTime: 2024/07/18 18:03:50
都是这种格式，如何找到是那个文件？

**Comment by yuany3721** [comment]
> The log has provided a hint that the `date` format in the `frontmatter` of your `.md` file is incorrect.
> 
> In YAML, the date format supports standard `UTC` and `ISO` time formats, so please check if your format is correct.
> 
> The theme does not use the `date` field by default.

In `1.0.0-rc.136`, this bug still alive. While `createTime` as format `1234-56-78`, this bug still occurs when compliling. The theme seems only accept format like this `1234/56/78`, and the time follows does not  affect the bug. @pengzhanbo
